apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmao-treino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmao-treino
  template:
    metadata:
      labels:
        app: irmao-treino
    spec:
      containers:
      - name: irmao-treino
        image: ricardomms/irmaotreino:latest
        ports:
        - containerPort: 80

