apiVersion: apps/v1
kind: Deployment
metadata:
  name: treino-deployment
spec:
  selector:
    matchLabels:
      app: treino
  template:
    metadata:
      labels:
        app: treino
    spec:
      containers:
      - name: treino
        image: ricardomms10/irmao-treino:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: treino-service
spec:
  type: NodePort
  selector:
    app: treino
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
